### ISSUE TITLE
helm install lost generate-name

### ISSUE THREAD

**Issue by yellow456434** [MicrosoftDocs/azure-docs.zh-tw#613]
I use helm to insall, in zsh will show miss generate-name error

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 597ba957-9501-5919-73a0-6d47b1ca2c6d
* Version Independent ID: 6345fa19-b3f2-ffd6-f526-908f845b51f6
* Content: [使用自有的 TLS 憑證來輸入 Azure Kubernetes Service (AKS) 叢集](https://docs.microsoft.com/zh-tw/azure/aks/ingress-own-tls)
* Content Source: [articles/aks/ingress-own-tls.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/master/articles/aks/ingress-own-tls.md)
* Service: **container-service**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by srvbpigh** [comment]
Hello, @yellow456434
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #48286](https://github.com/MicrosoftDocs/azure-docs/issues/48286) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @yellow456434, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/48286. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
