### ISSUE TITLE
Remote build won't happen on Linux when using WEBSITE_RUN_FROM_PACKAGE

### ISSUE THREAD

**Issue by shawnswlin** [MicrosoftDocs/azure-docs.zh-tw#616]
I'm having a problem with remote build on Linux host for python based functionapp. 
After specifying ENABLE_ORYX_BUILD, 
SCM_DO_BUILD_DURING_DEPLOYMENT and WEBSITE_RUN_FROM_PACKAGE, 3rd-party packages in requirement.txt still could not be imported.

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 4dc400d6-feaf-3239-094e-3c19aae44345
* Version Independent ID: aabb7db4-27fc-63c9-b019-d116450c439f
* Content: [Azure 函數中的部署技術](https://docs.microsoft.com/zh-tw/azure/azure-functions/functions-deployment-technologies)
* Content Source: [articles/azure-functions/functions-deployment-technologies.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/master/articles/azure-functions/functions-deployment-technologies.md)
* GitHub Login: @georgewallace
* Microsoft Alias: **gwallace**

**Comment by srvbpigh** [comment]
Hello, @shawnswlin
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #52501](https://github.com/MicrosoftDocs/azure-docs/issues/52501) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @shawnswlin, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/52501. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
