### ISSUE TITLE
add nodepool have error

### ISSUE THREAD

**Issue by yellow456434** [MicrosoftDocs/azure-docs.zh-tw#617]
when I type this command
az aks nodepool add \
    --resource-group test \
    --cluster-name testAKS \
    --os-type Windows \
    --name npwin \
    --node-count 1 \
    --kubernetes-version 1.15.10

will show to error
Operation failed with status: 'Bad Request'. Details: Windows profile definition is missing for the cluster.
how to solve?

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 6de70aec-9ebe-5655-6657-5c171de374b1
* Version Independent ID: c9eb35c8-8703-511b-987b-e2a441be2e47
* Content: [在 Azure Kubernetes Service （AKS）叢集上建立 Windows Server 容器](https://docs.microsoft.com/zh-tw/azure/aks/windows-container-cli)
* Content Source: [articles/aks/windows-container-cli.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/master/articles/aks/windows-container-cli.md)
* GitHub Login: @olprod

**Comment by srvbpigh** [comment]
Hello, @yellow456434
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #54362](https://github.com/MicrosoftDocs/azure-docs/issues/54362) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @yellow456434, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/54362. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
