### ISSUE TITLE
This document has the error, the service principal "Microsoft.StorageSync" not exist

### ISSUE THREAD

**Issue by t106362512** [MicrosoftDocs/azure-docs.zh-tw#619]
The service principal "Microsoft.StorageSync" not exist, it should be changed to the "Storage Resource Provider".

link: 
https://docs.microsoft.com/zh-tw/azure/storage/files/storage-sync-files-troubleshoot?tabs=portal1%2Cazure-portal#troubleshoot-rbac

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 7235bd07-1172-ac6a-3dab-0200fd73bd87
* Version Independent ID: 9620b286-fe9e-0c56-c01f-ddf7c3c36ac0
* Content: [對 Azure 檔案同步進行疑難排解](https://docs.microsoft.com/zh-tw/azure/storage/files/storage-sync-files-troubleshoot?tabs=portal1%2Cazure-portal#feedback)
* Content Source: [articles/storage/files/storage-sync-files-troubleshoot.md](https://github.com/MicrosoftDocs/azure-docs.zh-tw/blob/master/articles/storage/files/storage-sync-files-troubleshoot.md)
* Service: **storage**
* Sub-service: **files**
* GitHub Login: @jeffpatt24
* Microsoft Alias: **jeffpatt**

**Comment by srvbpigh** [comment]
Hello, @t106362512
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @t106362512, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/55414. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
